version: '3.8'

services:
  blocky-maze-app:
    build: .
    image: blocky-maze-app
    container_name: blocky-maze-app
    entrypoint: /bin/bash ./entrypoint.sh
    environment:
      - LIBGL_ALWAYS_SOFTWARE=1
      - BLOCKY_OBJECTIVES=${BLOCKY_OBJECTIVES:-GATED}
      - BLOCKY_WRAP=${BLOCKY_WRAP:-true}
    ports:
      - "6080:6080"
    volumes:
      - .:/app
      - /app/blocky_game/target
      - /app/blocky_momot/target
      - /app/blocky_model/target
